# config.yaml
server:
  address: ":8080"
  timeout: 30s

logging:
  environment: "development"
  file_path: "./logs/app.log"
  console: true

milvus:
  address: "localhost:19530"
  username: ""
  password: ""
  collection_name: "enterprise_docs"
  tls:
    enabled: false
    cert_path: ""

embedding:
  model_name: "text-embedding-3-small"
  api_key: "your-api-key"
  timeout: 15s

deepseek:
  base_url: "http://localhost:5000"
  api_key: "your-deepseek-key"
  model: "deepseek-local"
  timeout: 30s

document:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size: "10MB"