# config.yaml
server:
  address: ":8080"
  timeout: 30s

logging:
  environment: "development"
  file_path: "./logs/app.log"
  console: true

milvus:
  address: "localhost:19530"
  username: ""
  password: ""
  collection_name: "enterprise_docs"
  tls:
    enabled: false
    cert_path: ""

embedding:
  model_name: "all-MiniLM-L6-v2"
  api_url: "http://localhost:8081/embed"
  api_key: "dummy"
  timeout: 30s

deepseek:
  base_url: "http://localhost:11434"
  api_key: "dummy-key"
  model: "deepseek-r1:1.5b"
  timeout: 30s

document:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size: "10MB"